import { Router } from "express";

export const currenciesRouter = Router();


const data = [
    {
      "id": "udon",
      "name": "Udonex",
      "description": null,
      "homepage": null,
      "price": "0.001",
      "blockchain_key": "bsc-main",
      "explorer_transaction": "https://bscscan.com/tx/#{txid}",
      "explorer_address": "https://bscscan.com/address/#{address}",
      "type": "coin",
      "deposit_enabled": true,
      "withdrawal_enabled": true,
      "deposit_fee": "0.0",
      "min_deposit_amount": "10000.0",
      "withdraw_fee": "1.0",
      "min_withdraw_amount": "100.0",
      "withdraw_limit_24h": "0.0",
      "withdraw_limit_72h": "0.0",
      "base_factor": 1000000,
      "precision": 6,
      "position": 1,
      "icon_url": "https://i.imgur.com/fr9hr5t.png",
      "min_confirmations": 30
    },
    {
      "id": "btc",
      "name": "Bitcoin",
      "description": null,
      "homepage": null,
      "price": "1.0",
      "blockchain_key": "btc-main",
      "explorer_transaction": "https://www.blockchain.com/btc/tx/#{txid}",
      "explorer_address": "https://www.blockchain.com/btc/address/#{address}",
      "type": "coin",
      "deposit_enabled": false,
      "withdrawal_enabled": true,
      "deposit_fee": "0.0",
      "min_deposit_amount": "0.0005",
      "withdraw_fee": "0.001",
      "min_withdraw_amount": "0.0000001",
      "withdraw_limit_24h": "0.0",
      "withdraw_limit_72h": "0.0",
      "base_factor": 100000000,
      "precision": 6,
      "position": 2,
      "icon_url": "https://s2.coinmarketcap.com/static/img/coins/128x128/1.png",
      "min_confirmations": 1
    },
    {
      "id": "bnb",
      "name": "Binance BSC",
      "description": null,
      "homepage": null,
      "price": "1.0",
      "blockchain_key": "bsc-main",
      "explorer_transaction": "https://bscscan.com/tx/#{txid}",
      "explorer_address": "https://bscscan.com/address/#{address}",
      "type": "coin",
      "deposit_enabled": true,
      "withdrawal_enabled": true,
      "deposit_fee": "0.0",
      "min_deposit_amount": "0.005",
      "withdraw_fee": "0.005",
      "min_withdraw_amount": "0.1",
      "withdraw_limit_24h": "2.0",
      "withdraw_limit_72h": "2.0",
      "base_factor": 1000000000000000000,
      "precision": 6,
      "position": 4,
      "icon_url": "https://s2.coinmarketcap.com/static/img/coins/128x128/1839.png",
      "min_confirmations": 30
    },
    {
      "id": "wbtc",
      "name": "Wrapped BTC",
      "description": null,
      "homepage": null,
      "price": "1.0",
      "blockchain_key": "eth-main",
      "explorer_transaction": "https://etherscan.io/tx/#{txid}",
      "explorer_address": "https://etherscan.io/address/#{address}",
      "type": "coin",
      "deposit_enabled": true,
      "withdrawal_enabled": true,
      "deposit_fee": "0.0",
      "min_deposit_amount": "0.0001",
      "withdraw_fee": "0.0",
      "min_withdraw_amount": "0.001",
      "withdraw_limit_24h": "0.0",
      "withdraw_limit_72h": "0.0",
      "base_factor": 100000000,
      "precision": 6,
      "position": 5,
      "icon_url": "https://s2.coinmarketcap.com/static/img/coins/128x128/3717.png",
      "min_confirmations": 30
    },
    {
      "id": "busd-bep20",
      "name": "Binance-Peg BUSD",
      "description": null,
      "homepage": null,
      "price": "1.0",
      "blockchain_key": "bsc-main",
      "explorer_transaction": "https://bscscan.com/tx/#{txid}",
      "explorer_address": "https://bscscan.com/address/#{address}",
      "type": "coin",
      "deposit_enabled": true,
      "withdrawal_enabled": true,
      "deposit_fee": "0.0",
      "min_deposit_amount": "50.0",
      "withdraw_fee": "1.0",
      "min_withdraw_amount": "20.0",
      "withdraw_limit_24h": "500.0",
      "withdraw_limit_72h": "500.0",
      "base_factor": 1000000000000000000,
      "precision": 6,
      "position": 6,
      "icon_url": "https://s2.coinmarketcap.com/static/img/coins/128x128/4687.png",
      "min_confirmations": 30
    },
    {
      "id": "busd",
      "name": "Binance USD",
      "description": null,
      "homepage": null,
      "price": "1.0",
      "blockchain_key": "eth-main",
      "explorer_transaction": "https://etherscan.io/tx/#{txid}",
      "explorer_address": "https://etherscan.io/address/#{address}",
      "type": "coin",
      "deposit_enabled": true,
      "withdrawal_enabled": true,
      "deposit_fee": "0.0",
      "min_deposit_amount": "50.0",
      "withdraw_fee": "0.0",
      "min_withdraw_amount": "20.0",
      "withdraw_limit_24h": "500.0",
      "withdraw_limit_72h": "500.0",
      "base_factor": 1000000000000000000,
      "precision": 6,
      "position": 7,
      "icon_url": "https://s2.coinmarketcap.com/static/img/coins/128x128/4687.png",
      "min_confirmations": 30
    },
    {
      "id": "eth",
      "name": "Ethereum",
      "description": null,
      "homepage": null,
      "price": "1.0",
      "blockchain_key": "eth-main",
      "explorer_transaction": "https://etherscan.io/tx/#{txid}",
      "explorer_address": "https://etherscan.io/address/#{address}",
      "type": "coin",
      "deposit_enabled": true,
      "withdrawal_enabled": true,
      "deposit_fee": "0.0",
      "min_deposit_amount": "0.01",
      "withdraw_fee": "0.005",
      "min_withdraw_amount": "0.05",
      "withdraw_limit_24h": "2.0",
      "withdraw_limit_72h": "2.0",
      "base_factor": 1000000000000000000,
      "precision": 6,
      "position": 8,
      "icon_url": "https://s2.coinmarketcap.com/static/img/coins/128x128/1027.png",
      "min_confirmations": 30
    },
    {
      "id": "eth-bep20",
      "name": "Binance-Peg Ethereum",
      "description": null,
      "homepage": null,
      "price": "1.0",
      "blockchain_key": "bsc-main",
      "explorer_transaction": "https://bscscan.com/tx/#{txid}",
      "explorer_address": "https://bscscan.com/address/#{address}",
      "type": "coin",
      "deposit_enabled": true,
      "withdrawal_enabled": true,
      "deposit_fee": "0.0",
      "min_deposit_amount": "0.01",
      "withdraw_fee": "0.005",
      "min_withdraw_amount": "0.05",
      "withdraw_limit_24h": "0.0",
      "withdraw_limit_72h": "0.0",
      "base_factor": 1000000000000000000,
      "precision": 6,
      "position": 9,
      "min_confirmations": 30
    }]



currenciesRouter.get('/' , (req , res) => res.json({ ok : data }) )
